#!/usr/bin/env bash
# Usage: build
#
# Run go build with godep
#
# Author: Jingwen Owen Ou
# Modified: Matthew Rothenberg

if [ ! -x $GOPATH/bin/godep ]; then
  script/bootstrap
fi

$GOPATH/bin/godep go build -o bin/scmpuff
