#!/usr/bin/env bash
# Usage: build
#
# Run go build without dependencies.

TARGET="bin/scmpuff"
if [[ $OS == Windows* ]]; then
    TARGET="bin/scmpuff.exe"
fi

go build -o "$TARGET" -ldflags "-X main.VERSION=`./script/version`"
