#!/usr/bin/env bash
# Define build version when not using goxc for distribution builds
set -e

version="$(git describe --tags HEAD 2>/dev/null || true)"
if [ -z "$version" ]; then
  version="v0.?.? (build script error)"
fi

echo "${version#v}"
